# We want to validate the username var to prevent sudo rules getting created as
# users like ALL or root. Problem with the below list is rn I'll have to
# remember to update it by hand when they add a new lgsm servers.
accepted_usernames:
  - acserver
  - ahlserver
  - ahl2server
  - arkserver
  - arma3server
  - armarserver
  - atsserver
  - avserver
  - bbserver
  - bb2server
  - bdserver
  - bf1942server
  - bfvserver
  - bmdmserver
  - boserver
  - bsserver
  - btserver
  - btlserver
  - ccserver
  - ckserver
  - cmwserver
  - codserver
  - cod2server
  - cod4server
  - coduoserver
  - codwawserver
  - colserver
  - csserver
  - cs2server
  - csczserver
  - csgoserver
  - cssserver
  - ctserver
  - dabserver
  - dayzserver
  - dmcserver
  - dodserver
  - dodrserver
  - dodsserver
  - doiserver
  - dstserver
  - dysserver
  - ecoserver
  - emserver
  - etlserver
  - ets2server
  - fctrserver
  - fofserver
  - gmodserver
  - hcuserver
  - hl2dmserver
  - hldmserver
  - hldmsserver
  - hwserver
  - hzserver
  - insserver
  - inssserver
  - iosserver
  - jc2server
  - jc3server
  - jk2server
  - kfserver
  - kf2server
  - l4dserver
  - l4d2server
  - mcserver
  - mcbserver
  - mhserver
  - mohaaserver
  - momserver
  - mtaserver
  - ndserver
  - necserver
  - nmrihserver
  - nsserver
  - ns2server
  - ns2cserver
  - ohdserver
  - onsetserver
  - opforserver
  - pcserver
  - pc2server
  - pmcserver
  - psserver
  - pvkiiserver
  - pvrserver
  - pwserver
  - pzserver
  - q2server
  - q3server
  - q4server
  - qlserver
  - qwserver
  - ricochetserver
  - roserver
  - rtcwserver
  - rustserver
  - rwserver
  - sampserver
  - sbserver
  - sbotsserver
  - scpslserver
  - scpslsmserver
  - sdtdserver
  - sfserver
  - sfcserver
  - sof2server
  - solserver
  - squadserver
  - stserver
  - stnserver
  - svenserver
  - terrariaserver
  - tfserver
  - tf2server
  - tfcserver
  - tiserver
  - tsserver
  - ts3server
  - tuserver
  - twserver
  - untserver
  - utserver
  - ut2k4server
  - ut3server
  - ut99server
  - vhserver
  - vintsserver
  - vpmcserver
  - vsserver
  - wetserver
  - wfserver
  - wmcserver
  - wurmserver
  - zmrserver
  - zpsserver
