game_servers = {'acserver': 'Assetto Corsa',
 'ahl2server': 'Action: Source',
 'ahlserver': 'Action Half-Life',
 'arkserver': 'ARK: Survival Evolved',
 'arma3server': 'ARMA 3',
 'armarserver': 'Arma Reforger',
 'avserver': 'Avorion',
 'bb2server': 'BrainBread 2',
 'bbserver': 'BrainBread',
 'bdserver': 'Base Defense',
 'bf1942server': 'Battlefield 1942',
 'bfvserver': 'Battlefield: Vietnam',
 'bmdmserver': 'Black Mesa: Deathmatch',
 'boserver': 'Ballistic Overkill',
 'bsserver': 'Blade Symphony',
 'bt1944server': 'Battalion 1944',
 'btserver': 'Barotrauma',
 'ccserver': 'Codename CURE',
 'cdserver': 'Crafting Dead',
 'cmwserver': 'Chivalry: Medieval Warfare',
 'cod2server': 'Call of Duty 2',
 'cod4server': 'Call of Duty 4',
 'codserver': 'Call of Duty',
 'coduoserver': 'Call of Duty: United Offensive',
 'codwawserver': 'Call of Duty: World at War',
 'colserver': 'Colony Survival',
 'csczserver': 'Counter-Strike: Condition Zero',
 'csgoserver': 'Counter-Strike: Global Offensive',
 'csserver': 'Counter-Strike 1.6',
 'cssserver': 'Counter-Strike: Source',
 'dabserver': 'Double Action: Boogaloo',
 'dayzserver': 'DayZ',
 'dmcserver': 'Deathmatch Classic',
 'dodrserver': 'Day of Dragons',
 'dodserver': 'Day of Defeat',
 'dodsserver': 'Day of Defeat: Source',
 'doiserver': 'Day of Infamy',
 'dstserver': "Dont Starve Together",
 'dysserver': 'Dystopia',
 'ecoserver': 'Eco',
 'emserver': 'Empires Mod',
 'etlserver': 'ET: Legacy',
 'fctrserver': 'Factorio',
 'fofserver': 'Fistful of Frags',
 'gmodserver': 'Garrys Mod',
 'hl2dmserver': 'Half-Life 2: Deathmatch',
 'hldmserver': 'Half-Life: Deathmatch',
 'hldmsserver': 'Half-Life Deathmatch: Source',
 'hwserver': 'Hurtworld',
 'insserver': 'Insurgency',
 'inssserver': 'Insurgency: Sandstorm',
 'iosserver': 'IOSoccer',
 'jc2server': 'Just Cause 2',
 'jc3server': 'Just Cause 3',
 'jk2server': 'Jedi Knight II: Jedi Outcast',
 'kf2server': 'Killing Floor 2',
 'kfserver': 'Killing Floor',
 'l4d2server': 'Left 4 Dead 2',
 'l4dserver': 'Left 4 Dead',
 'loserver': 'Last Oasis',
 'mcbserver': 'Minecraft Bedrock',
 'mcserver': 'Minecraft',
 'mhserver': 'MORDHAU',
 'mohaaserver': 'Medal of Honor: Allied Assault',
 'momserver': 'Memories of Mars',
 'mtaserver': 'Multi Theft Auto',
 'mumbleserver': 'Mumble',
 'ndserver': 'Nuclear Dawn',
 'necserver': 'Necesse',
 'nmrihserver': 'No More Room in Hell',
 'ns2cserver': 'NS2: Combat',
 'ns2server': 'Natural Selection 2',
 'nsserver': 'Natural Selection',
 'onsetserver': 'Onset',
 'opforserver': 'Opposing Force',
 'pc2server': 'Project Cars 2',
 'pcserver': 'Project Cars',
 'pmcserver': 'PaperMC',
 'pstbsserver': 'Post Scriptum: The Bloody Seventh',
 'pvkiiserver': 'Pirates Vikings and Knights II',
 'pvrserver': 'Pavlov VR',
 'pzserver': 'Project Zomboid',
 'q2server': 'Quake 2',
 'q3server': 'Quake 3: Arena',
 'qlserver': 'Quake Live',
 'qwserver': 'Quake World',
 'ricochetserver': 'Ricochet',
 'roserver': 'Red Orchestra: Ostfront 41-45',
 'rtcwserver': 'Return to Castle Wolfenstein',
 'rustserver': 'Rust',
 'rwserver': 'Rising World',
 'sampserver': 'San Andreas Multiplayer',
 'sbotsserver': 'StickyBots',
 'sbserver': 'Starbound',
 'scpslserver': 'SCP: Secret Laboratory',
 'scpslsmserver': 'SCP: Secret Laboratory ServerMod',
 'sdtdserver': '7 Days to Die',
 'sfcserver': 'SourceForts Classic',
 'sfserver': 'Satisfactory',
 'sof2server': 'Soldier Of Fortune 2: Gold Edition',
 'solserver': 'Soldat',
 'squadserver': 'Squad',
 'stnserver': 'Survive the Nights',
 'stserver': 'Stationeers',
 'svenserver': 'Sven Co-op',
 'terrariaserver': 'Terraria',
 'tf2server': 'Team Fortress 2',
 'tfcserver': 'Team Fortress Classic',
 'tiserver': 'The Isle',
 'ts3server': 'Teamspeak 3',
 'tsserver': 'The Specialists',
 'tuserver': 'Tower Unite',
 'twserver': 'Teeworlds',
 'untserver': 'Unturned',
 'ut2k4server': 'Unreal Tournament 2004',
 'ut3server': 'Unreal Tournament 3',
 'ut99server': 'Unreal Tournament 99',
 'utserver': 'Unreal Tournament',
 'vhserver': 'Valheim',
 'vintsserver': 'Vintage Story',
 'vpmcserver': 'Velocity Proxy MC',
 'vsserver': 'Vampire Slayer',
 'wetserver': 'Wolfenstein: Enemy Territory',
 'wfserver': 'Warfork',
 'wmcserver': 'WaterfallMC',
 'wurmserver': 'Wurm Unlimited',
 'zmrserver': 'Zombie Master: Reborn',
 'zpsserver': 'Zombie Panic! Source'}
