- name: Ensure required sudoers rules are in place for new user
  community.general.sudoers:
    name: "{{ sudo_rule_name }}"
    user: "{{ web_lgsm_user }}"
    host: "ALL"
    runas: "{{ gs_user }}"
    nopassword: true
    commands:
      - "{{ script_paths }}"
      - /usr/bin/watch
      - /usr/bin/tmux
      - /usr/bin/kill
    state: present
  when: same_user is not defined or same_user == false
