- name: Add temporary {{ username }} sudoers rule for game server auto install
  community.general.sudoers:
    name: "{{ username }}-temp-auto-install"
    user: "{{ username }}"
    host: "ALL"
    runas: root
    nopassword: true
    commands: ALL
    state: present
  when: same_user is not defined or same_user == false
