"""Rename GameServer model to GameServerModel to avoid confusion under new clean arch framework

Revision ID: 17554acb8d01
Revises: c2fb7a90e6db
Create Date: 2026-03-01 13:17:25.543917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17554acb8d01'
down_revision = 'c2fb7a90e6db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('game_server', 'game_server_model')

    with op.batch_alter_table('audit_model', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_audit_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_audit_model_id'), ['id'])

    with op.batch_alter_table('cron_model', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_job_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_cron_model_id'), ['id'])
        batch_op.drop_constraint(batch_op.f('fk_job_server_id_game_server'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_cron_model_server_id_game_server_model'), 'game_server_model', ['server_id'], ['id'])

    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_model_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_model_username'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    with op.batch_alter_table('cron_model', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cron_model_server_id_game_server_model'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_job_server_id_game_server'), 'game_server', ['server_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_cron_model_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_job_id'), ['id'])

    with op.batch_alter_table('audit_model', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_audit_model_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_audit_id'), ['id'])

    op.rename_table('game_server_model', 'game_server')
    # ### end Alembic commands ###
