"""Rename Audit model to AuditModel to avoid confusion under new clean arch framework

Revision ID: 29c66f892ca8
Revises: 318979a51d1a
Create Date: 2026-02-16 15:37:58.714718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c66f892ca8'
down_revision = '318979a51d1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_model',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('message', sa.String(length=150), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_audit_model_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_model')),
    sa.UniqueConstraint('id', name=op.f('uq_audit_model_id'))
    )
    op.drop_table('audit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('message', sa.VARCHAR(length=150), nullable=True),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_audit_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit')),
    sa.UniqueConstraint('id', name=op.f('uq_audit_id'))
    )
    op.drop_table('audit_model')
    # ### end Alembic commands ###
