"""Rename Audit model to AuditModel to avoid confusion under new clean arch framework

Revision ID: 29c66f892ca8
Revises: 318979a51d1a
Create Date: 2026-02-16 15:37:58.714718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c66f892ca8'
down_revision = '318979a51d1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('audit', 'audit_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('audit_model', 'audit')
    # ### end Alembic commands ###
