"""add new fields and methods to User model for 2fa support

Revision ID: 2defb742f1de
Revises: 6f1dce569562
Create Date: 2025-08-30 19:56:15.908444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2defb742f1de'
down_revision = '6f1dce569562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_secret', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('otp_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('otp_setup', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('otp_secret')
        batch_op.drop_column('otp_enabled')
        batch_op.drop_column('otp_setup')

    # ### end Alembic commands ###
