"""add install_failed to GameServer model

Revision ID: 318979a51d1a
Revises: 21cb6d4b6616
Create Date: 2025-11-01 18:38:50.538514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318979a51d1a'
down_revision = '21cb6d4b6616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_server', schema=None) as batch_op:
        batch_op.add_column(sa.Column('install_failed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_server', schema=None) as batch_op:
        batch_op.drop_column('install_failed')

    # ### end Alembic commands ###
