"""add Jobs class/table

Revision ID: 592b30a8d8c9
Revises: aa0ff60b5509
Create Date: 2025-06-29 16:30:34.497878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592b30a8d8c9'
down_revision = 'aa0ff60b5509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('server_id', sa.String(length=36), nullable=False),
    sa.Column('command', sa.String(length=150), nullable=True),
    sa.Column('comment', sa.String(length=150), nullable=True),
    sa.Column('expression', sa.String(length=150), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['game_server.id'], name=op.f('fk_job_server_id_game_server')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job')),
    sa.UniqueConstraint('id', name=op.f('uq_job_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    # ### end Alembic commands ###
