"""Change AuditModel backref to new UserModel

Revision ID: 68eae21663b8
Revises: e1381fdc7e43
Create Date: 2026-02-22 21:47:34.381548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68eae21663b8'
down_revision = 'e1381fdc7e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_model', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_audit_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_audit_user_id_user_model'), 'user_model', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_model', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_audit_user_id_user_model'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_audit_user_id_user'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
