"""remove unique constraint from GameServer install_name

Revision ID: 6f1dce569562
Revises: ef9d6478fcfe
Create Date: 2025-07-12 19:30:32.763194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f1dce569562'
down_revision = 'ef9d6478fcfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_server', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_game_server_install_name'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_server', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_game_server_install_name'), ['install_name'])

    # ### end Alembic commands ###
