"""Initial migrate

Revision ID: 83095689301a
Revises: 
Create Date: 2025-04-21 12:06:16.177930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83095689301a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_server',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('install_name', sa.String(length=150), nullable=True),
    sa.Column('install_path', sa.String(length=150), nullable=True),
    sa.Column('script_name', sa.String(length=150), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('is_container', sa.Boolean(), nullable=True),
    sa.Column('install_type', sa.String(length=150), nullable=True),
    sa.Column('install_host', sa.String(length=150), nullable=True),
    sa.Column('install_finished', sa.Boolean(), nullable=True),
    sa.Column('keyfile_path', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_server')),
    sa.UniqueConstraint('id', name=op.f('uq_game_server_id')),
    sa.UniqueConstraint('install_name', name=op.f('uq_game_server_install_name'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=150), nullable=True),
    sa.Column('role', sa.String(length=150), nullable=True),
    sa.Column('permissions', sa.String(length=600), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('img_path', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('game_server')
    # ### end Alembic commands ###

