"""Remove img_path from user

Revision ID: aa0ff60b5509
Revises: 83095689301a
Create Date: 2025-04-21 19:40:47.204567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa0ff60b5509'
down_revision = '83095689301a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('img_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_path', sa.VARCHAR(length=150), nullable=True))

    # ### end Alembic commands ###

