"""Rename User model to UserModel to avoid confusion under new clean arch framework

Revision ID: c2fb7a90e6db
Revises: 68eae21663b8
Create Date: 2026-02-22 21:27:00.522643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2fb7a90e6db'
down_revision = '68eae21663b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('user', 'user_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('user_model', 'user')
    # ### end Alembic commands ###
