"""Rename expression in CronModel to schedule to be polymorphic

Revision ID: e1381fdc7e43
Revises: f867303c1b5e
Create Date: 2026-02-21 16:41:11.788359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1381fdc7e43'
down_revision = 'f867303c1b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cron_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule', sa.String(length=150), nullable=True))
        batch_op.drop_column('expression')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cron_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expression', sa.VARCHAR(length=150), nullable=True))
        batch_op.drop_column('schedule')

    # ### end Alembic commands ###
