"""add sort_order to GameServerModel

Revision ID: ebdadd8d2583
Revises: 17554acb8d01
Create Date: 2026-03-21 13:55:08.386950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebdadd8d2583'
down_revision = '17554acb8d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_server_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_game_server_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_game_server_model_id'), ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_server_model', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_game_server_model_id'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_game_server_id'), ['id'])
        batch_op.drop_column('sort_order')

    # ### end Alembic commands ###
