"""Create new Audit table

Revision ID: ef9d6478fcfe
Revises: 592b30a8d8c9
Create Date: 2025-07-06 21:06:51.010867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef9d6478fcfe'
down_revision = '592b30a8d8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.String(length=150), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_audit_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit')),
    sa.UniqueConstraint('id', name=op.f('uq_audit_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit')
    # ### end Alembic commands ###
