"""Rename Cron model to CronModel to avoid confusion under new clean arch framework

Revision ID: f867303c1b5e
Revises: 29c66f892ca8
Create Date: 2026-02-21 16:20:13.387048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f867303c1b5e'
down_revision = '29c66f892ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cron_model',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('server_id', sa.String(length=36), nullable=False),
    sa.Column('command', sa.String(length=150), nullable=True),
    sa.Column('comment', sa.String(length=150), nullable=True),
    sa.Column('expression', sa.String(length=150), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['game_server.id'], name=op.f('fk_cron_model_server_id_game_server')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cron_model')),
    sa.UniqueConstraint('id', name=op.f('uq_cron_model_id'))
    )
    op.drop_table('job')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('server_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('command', sa.VARCHAR(length=150), nullable=True),
    sa.Column('comment', sa.VARCHAR(length=150), nullable=True),
    sa.Column('expression', sa.VARCHAR(length=150), nullable=True),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['game_server.id'], name=op.f('fk_job_server_id_game_server')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job')),
    sa.UniqueConstraint('id', name=op.f('uq_job_id'))
    )
    op.drop_table('cron_model')
    # ### end Alembic commands ###
