"""Rename Cron model to CronModel to avoid confusion under new clean arch framework

Revision ID: f867303c1b5e
Revises: 29c66f892ca8
Create Date: 2026-02-21 16:20:13.387048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f867303c1b5e'
down_revision = '29c66f892ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('job', 'cron_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('cron_model', 'job')
    # ### end Alembic commands ###
