from .add import AddForm
from .settings import SettingsForm
from .save import SaveForm
from .download import DownloadForm
from .upload import UploadForm
from .select_cfg import SelectCfgForm
from .send_command import SendCommandForm
from .server_control import ServerControlForm
from .jobs import JobsForm
