---
## Playbook required vars.
# gs_user
# script_paths
# sudo_rule_name
# web_lgsm_user

- name: Runs sudo rule creation for /add existing game servers page
  hosts: localhost
  become: true
  connection: local
  vars:
    # Same user defaults to false, meaning default create new user.
    same_user: false
    setup: false
  vars_files:
    - vars/accepted_gs_users.yml

  tasks:
    - name: Include sub tasks
      include_tasks: "{{ item }}"
      loop:
        - tasks/validate_gs_user.yml
        - tasks/create_gs_user_group.yml
        - tasks/add_weblgsm_to_gs_group.yml
        - tasks/add_sudoers_rules.yml
        - tasks/fix_sudoers_rule.yml
...
