---
- name: Ensure specific sudo rule is present in sudoers
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Ensure the sudoers rule is present
      community.general.sudoers:
        name: "{{ sudo_rule_name }}"
        user: "{{ web_lgsm_user }}"
        host: "ALL"
        runas: "{{ gs_user }}"
        nopassword: true
        commands: "{{ sudo_commands }}"
        state: present
...
