FROM ubuntu:jammy
ENV CONTAINER=YES
ENV UID=1000
ENV GID=1000

# Install apt deps.
RUN dpkg --add-architecture i386 && apt-get update && apt-get upgrade -y && apt-get install -y sudo apt-utils iproute2

# First add the web-lgsm group.
RUN groupadd -g $GID web-lgsm

# Then create the user and add them to the group.
RUN useradd -u $UID -g $GID -r -d /home/web-lgsm -s /bin/bash web-lgsm

RUN mkdir -p /etc/sudoers.d

# Temp allow 'web-lgsm' to use sudo without a password.
RUN echo "web-lgsm ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# Set the working directory.
WORKDIR /home/web-lgsm

# Copy the app source code.
COPY . /home/web-lgsm

# Set ownership of the app directory to the web-lgsm user.
RUN chown -R web-lgsm:web-lgsm /home/web-lgsm

# Set the default user to 'web-lgsm'.
USER web-lgsm
ENV USER=web-lgsm

# Install web-lgsm.
RUN /home/web-lgsm/install.sh -d

# Delete temp sudoers rule.
USER root
RUN sed -i '$ d' /etc/sudoers

# Expose app's port.
EXPOSE 12357

USER web-lgsm
ENV USER=web-lgsm

ENTRYPOINT ["/home/web-lgsm/web-lgsm.py", "--start"]
